### ISSUE TITLE
Sublime Text 2 Hangs when a Terminal is Opened Via SublimeFiles

### ISSUE THREAD

**Issue by hindol** [al63/SublimeFiles#1]
I'm using Ubuntu Precise 12.04 x86 and Sublime Text 2 stable release.

Seems like ST2 waits for the terminal to quit. Because after I close the terminal, ST2 is responsive again. Please fix.

EDIT

Maybe use a subprocess to open the terminal? You can refer to this plugin - https://github.com/wbond/sublime_terminal/blob/master/Terminal.py. Unfortunately I don't know Python, :(, but this line looks interesting - "subprocess.Popen(args, cwd=dir.encode(encoding))" in "def run_terminal(self, dir, parameters):".

**Comment by al63** [comment]
Thanks for letting me know. Could you possibly tell me what terminal you are using? Also could you paste your "term_command" line (so i can recreate)

**Comment by hindol** [comment]
Sure. This is my settings file,

```
{
    //The command to execute to open a terminal.
    //Program will append the directory to open to the end of term_command.
    "term_command": "gnome-terminal --working-directory="
}
```

Note: On another machine with Ubuntu 64-bit, the same seems to work fine. I am using WebUpd8 ppa for Sublime Text 2 on both the machines.

**Comment by al63** [comment]
I just changed it to use Popen. Hopefully fixes your problem. If not, let me know.

**Comment by hindol** [comment]
Now works ok. Thanks, :)
