### ISSUE TITLE
Open file given full path

### ISSUE THREAD

**Issue by samselikoff** [al63/SublimeFiles#11]
Would it be possible to open a file by pasting in the full path & file name? For example, D:\work\test.txt.

**Comment by al63** [comment]
Yeah, totally doable. I'll add this sometime soon.

**Comment by al63** [comment]
Just pushed a change that lets you navigate to a specific directory (directory actions -> navigate to specific directory)

Let me know if this doesn't work for you.

**Comment by al63** [comment]
jk it is messed up.

**Comment by samselikoff** [comment]
you're the man! donate link?

**Comment by al63** [comment]
Haha don't worry about it. I'm just happy if people find the plugin useful.
