### ISSUE TITLE
ST3: Pressing Enter makes panel go away

### ISSUE THREAD

**Issue by ghost** [al63/SublimeFiles#14]
After invoking the file navigator, pressing `Enter` on any item/action makes the panel go away. Tested in ST3.

**Comment by al63** [comment]
Hi,

I'm pretty sure this plugin as is will not work at all in ST3 yet. I'll update this plugin to be ST3 compatible whenever sublime package control for ST3 is released. Sorry!

**Comment by ghost** [comment]
No problem, just reporting. Great plugin, I'll keep an eye on it.

**Comment by al63** [comment]
Appreciate it!

**Comment by jbowens** [comment]
:+1:

**Comment by Sv3n** [comment]
ST3 + SublimeFiles works with only a minor modification. Starting from the py3 branch, replace [line 65](https://github.com/al63/SublimeFiles/blob/d618aa9d48c5d46558172a22941133afd489ed74/sublime_files.py#L65) with

``` python
sublime.set_timeout(lambda: self.window.show_quick_panel(self.dir_files, self.handle_navigator_option, sublime.MONOSPACE_FONT), 10)
```

**Comment by al63** [comment]
Good find. Will change when I get home from work

**Comment by ghost** [comment]
Great job but I see it's already merged in the py3 branch. Directory actions still don't work, tho...

**Comment by al63** [comment]
Sorry guys, I just haven't spent any time at all dealing with this plugin and st3. And honestly, I'm not sure if I'm going to get around to it anytime soon. I welcome you guys to to fork and open your own pull requests, or just wait for me to get some free time :P.

**Comment by ghost** [comment]
Pretty [fixed](https://github.com/al63/SublimeFiles/commit/c927a30e5029061fed7f26543e50084227f27c46) now. Thanks guys.
