### ISSUE TITLE
it may not work when there are chinese in filename

### ISSUE THREAD

**Issue by asfdg21** [al63/SublimeFiles#2]
i use reload(sys)   sys.setdefaultencoding('utf8')  to fix it

**Comment by driftersoft** [comment]
yea, right now plugin chokes on non-ascii chars in paths, throwing UnicodeDecodeError.

alternative to the above would be to simply use os.getcwdu() instead of os.getcwd()

**Comment by al63** [comment]
Sorry, I neglected this. I'll fix this whenever i get some free time

**Comment by al63** [comment]
changed cwd to cwdu. let me know if you still have problems.
