### ISSUE TITLE
Error when no files are open

### ISSUE THREAD

**Issue by jotson** [al63/SublimeFiles#4]
Great plugin, thanks for making it.

One small bug... when I use the plugin to navigate files, then close all open windows, then try to navigate files again I get the following error:

`Traceback (most recent call last):
  File "./sublime_plugin.py", line 337, in run_
  File "./sublime_files.py", line 30, in run
    self.open_navigator()
  File "./sublime_files.py", line 54, in open_navigator
    if self.window.active_view().file_name() is not None:
AttributeError: 'NoneType' object has no attribute 'file_name'`

I fixed this by changing line 54 to:

`if self.window.active_view() is not None and self.window.active_view().file_name() is not None:`

**Comment by al63** [comment]
Good catch and thanks for providing a fix. Will go ahead and fix now
